-- The India-popular freshwater range: 102 products, 97 species profiles, four
-- new sections, and two sections that were announced and are now stocked.
--
-- Where the list came from. The shop owner asked for the catalogue to be
-- brought up to the breadth of a large online retailer's freshwater range
-- (liveaquaria.com, 583 listings, ~516 distinct after collapsing size- and
-- pack-variants, ~280 species). Asked how much of that to take, they chose "an
-- India-popular subset": the species Indian shops actually stock, not the whole
-- US range. What was deliberately left out, so nobody re-adds it by accident:
--
--   * GloFish and GFP axolotls. Transgenic animals; bringing a GMO into India
--     needs GEAC approval, and "GloFish" is a registered trademark besides.
--   * CITES-listed fish (e.g. zebra pleco L046, Appendix III) -- the Wildlife
--     (Protection) Amendment Act 2022 makes these a registration exercise, and
--     the Asian arowana rows already show what that looks like done honestly.
--   * Mosquitofish and dojo loach: established invasives, sold as feeders.
--   * Morph-by-morph listings (77 guppies, 25 bettas, 19 discus). Morphs fold
--     into one product per species, the rule V13 already set for arowana and V7
--     for Neocaridina. Goldfish are the exception, and deliberately: an oranda
--     and a comet are different purchases with different tanks and prices,
--     the same argument that justified four arowana rows. All six goldfish
--     point at ONE Carassius auratus profile.
--
-- Nothing here is copied from that retailer. Care figures are the commonly
-- published ranges for each species (facts, not prose); every summary and care
-- note is written for this shop, in centimetres, litres and rupees, and with the
-- two things an Indian customer needs that a US listing never says: what hard
-- borewell/municipal water does to a soft-water fish, and what a 32 C summer
-- does to a cool-water one.
--
-- INDIAN NATIVES are called out in their care notes, because six of these fish
-- are Indian and three are threatened at home: Denison barb (IUCN Endangered),
-- zebra loach (Western Ghats endemic) and pea puffer (IUCN Vulnerable, collected
-- out of Kerala's rivers for exactly this trade). Those listings say
-- captive-bred, and the shop has to mean it.
--
-- TWO NON-SPECIES, same honesty as V13's flowerhorn: scientific_name is NOT NULL,
-- so 'Hybrid (blood parrot cichlid)' and 'Symphysodon spp. (domestic strains)'
-- are explicit placeholders, and the care notes open by saying what they are.
-- Aquarium mollies are also multi-species hybrids; they sit under Poecilia
-- sphenops because that is the name the trade uses and the care is the same,
-- and the care note says so.
--
-- PRICES ARE ESTIMATES. Typical Indian retail for a shop-sized fish in 2026,
-- set by Claude from general market knowledge, not quoted from any supplier.
-- The owner asked for estimates and has not reviewed them yet.
--
-- image_key is NULL here and set by V18 in the same change as the photographs.
-- No inventory rows: stock lives in inventory-service and, like V13's fourteen,
-- these are catalogue-only until a tank is assigned.

-- ============================================================ sections ==

INSERT INTO category (slug, name, description, teaser, sort_order, parent_id, status)
SELECT v.slug, v.name, v.description, v.teaser, v.sort_order, c.id, 'ACTIVE'
  FROM category c, (VALUES
    ('goldfish', 'Goldfish',
     'Cool-water fish. They want more space, more filtration and cooler water than most tropicals -- and never a bowl.',
     'Oranda, ryukin, moor, ranchu.', 15),
    ('sharks-algae-eaters', 'Sharks & Algae Eaters',
     'Not sharks at all -- shark-shaped carp and loaches. Several grow large and several are territorial, so read the adult size first.',
     'Rainbow shark, SAE, bala.', 45),
    ('rainbowfish', 'Rainbowfish',
     'Schooling fish from Australia and New Guinea that colour up with age. Most prefer hard, alkaline water.',
     'Boesemani, praecox, threadfin.', 55),
    ('oddballs', 'Oddballs & Puffers',
     'Puffers, knifefish, spiny eels and bichirs. Specialist fish -- most need a tank of their own.',
     'Pea puffer, knifefish, fire eel.', 65)
  ) AS v(slug, name, description, teaser, sort_order)
 WHERE c.slug = 'freshwater';

-- Announced as COMING_SOON since V3/V5; they have stock now.
UPDATE category SET status = 'ACTIVE' WHERE slug IN ('cichlids-dwarf', 'tanganyika');

-- ===================================================== species profiles ==

INSERT INTO species_profile
 (scientific_name, common_name, max_size_cm, min_tank_litres, min_group_size,
  temp_min_c, temp_max_c, ph_min, ph_max, dgh_min, dgh_max,
  temperament, care_level, diet, plant_safe, animal_group, care_notes) VALUES
 ('Gymnocorymbus ternetzi', 'Black Skirt Tetra', 6.00, 80, 6, 22.0, 28.0, 6.0, 7.5, 4.0, 18.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'One of the toughest tetras in the trade and happy in anything from soft to moderately hard water, which makes it a good first fish for city tap water. In a group of three it bullies; in a group of eight it spends that energy on itself. Keep it away from bettas, guppies and angelfish. The long-fin and white forms are the same species. Dyed or "painted" skirts are injected with colour and we do not sell them.'),
 ('Hyphessobrycon eques', 'Serpae Tetra', 4.50, 80, 8, 22.0, 27.0, 6.0, 7.5, 4.0, 15.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A deep-red characin that looks best over dark substrate among plants. It is the fin-nipper of the tetra world: a big group turns the nipping inward into harmless sparring, a small one turns it on the rest of the tank. Fine with barbs, danios, corydoras and plecos; not with bettas, guppies, angelfish or fancy goldfish.'),
 ('Hemigrammus bleheri', 'Rummy Nose Tetra', 5.00, 100, 8, 24.0, 28.0, 5.5, 7.0, 2.0, 10.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Swims as one body in a way few tetras manage, and needs a longer tank to show it. The red on the head is a live indicator: bright means happy, washed-out pink means ammonia, nitrate or a temperature swing, usually before any test kit shows it. Prefers soft water, so if your supply is hard borewell water, blend with RO or rainwater. Sensitive to the first weeks of a new tank; add it to a matured one.'),
 ('Hemigrammus erythrozonus', 'Glowlight Tetra', 4.00, 60, 8, 24.0, 28.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A gentle, small tetra with a neon-orange stripe that almost disappears under bright white light and blazes under plants and floating cover. Peaceful with everything its own size, including shrimp adults. A good alternative to neons for a first community tank because it tolerates a wider range of water.'),
 ('Hyphessobrycon herbertaxelrodi', 'Black Neon Tetra', 4.00, 60, 8, 23.0, 27.0, 5.5, 7.5, 2.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Unrelated to the neon tetra despite the name, and easier to keep: it copes with slightly harder water and with the temperature swings of a room without air-conditioning. Active mid-water swimmer, peaceful, and a good shoal to put in before more delicate fish. Eats any small food.'),
 ('Moenkhausia pittieri', 'Diamond Tetra', 6.00, 100, 6, 24.0, 28.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Looks plain silver in a shop tank and develops its full sparkle and fin extensions over months in a settled, planted aquarium. Peaceful, sturdy, and slightly larger than most community tetras, so it is a good match for gouramis and corydoras. Soft plants may get the occasional nibble.'),
 ('Hyphessobrycon amandae', 'Ember Tetra', 2.00, 40, 10, 24.0, 28.0, 5.5, 7.0, 1.0, 10.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'One of the smallest fish we sell and one of the few fish that genuinely suits a 40-litre planted tank. Keep ten or more so they school rather than hide. Tiny mouth: feed crushed flake, micro pellets or baby brine shrimp. Adult shrimp are safe with them; shrimplets may not be.'),
 ('Phenacogrammus interruptus', 'Congo Tetra', 8.50, 150, 6, 24.0, 27.0, 6.0, 7.5, 3.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', FALSE, 'FISH',
  'Males reach 8 cm with trailing, fringed fins and a gold-to-blue sheen along the body; females are smaller and plainer. Nervous when kept in small numbers or bare tanks. Needs swimming length and soft to medium water. It will eat soft-leaved plants, so pair it with Anubias, Java fern and Cryptocoryne rather than delicate stems.'),
 ('Hyphessobrycon erythrostigma', 'Bleeding Heart Tetra', 6.00, 100, 6, 23.0, 28.0, 5.5, 7.0, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'A taller-bodied tetra with a red blotch behind the gills and a sail-like dorsal fin on males. Peaceful but not tiny, so it holds its own with gouramis and dwarf cichlids. Best in soft, slightly acidic water with leaf litter; colour dulls in hard water.'),
 ('Hyphessobrycon anisitsi', 'Buenos Aires Tetra', 7.00, 100, 6, 18.0, 28.0, 6.0, 8.0, 5.0, 25.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', FALSE, 'FISH',
  'A tough, fast tetra from the cooler south of South America that shrugs off hard water and a wide temperature range. The catch is its appetite: it strips soft plants to the stem. Keep it with plastic or tough plants, a big group, and tankmates that can keep up. Will nip slow, long-finned fish.'),
 ('Thayeria boehlkei', 'Penguin Tetra', 6.00, 80, 6, 22.0, 28.0, 6.0, 8.0, 4.0, 18.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Recognisable by its hockey-stick stripe and head-up swimming posture. Hardy, peaceful and adaptable to a wide pH range, which makes it an easy community fish. Keep it in a group; it becomes skittish alone.'),
 ('Pristella maxillaris', 'X-Ray Tetra', 4.50, 60, 6, 24.0, 28.0, 6.0, 8.0, 2.0, 20.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Tolerates harder water than most tetras -- in the wild it even enters slightly brackish water -- so it suits the hard tap supply in much of India. Translucent body, spine visible. Peaceful, active and undemanding. The gold form sold as "Gold Pristella" is the same species.'),
 ('Hemigrammus ocellifer', 'Head and Tail Light Tetra', 4.50, 60, 6, 22.0, 28.0, 6.0, 7.5, 2.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A long-standing favourite in Indian shops for a reason: cheap, tough, and it shows its reflective eye and tail spots best under dim light. Peaceful in a group of six or more. Good first-tank fish.'),
 ('Hyphessobrycon megalopterus', 'Black Phantom Tetra', 4.50, 60, 6, 22.0, 28.0, 6.0, 7.5, 2.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Males show a large black dorsal fin and display to each other in harmless mock fights; females have red-tinged fins. Peaceful toward other species, easy to feed and forgiving of beginner mistakes.'),
 ('Moenkhausia sanctaefilomenae', 'Red Eye Tetra', 7.00, 100, 6, 22.0, 28.0, 5.5, 8.0, 2.0, 20.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A robust, larger tetra that adapts to almost any tap water. Peaceful in a group, though a small group may nip long fins. Good dither fish for a tank of shy cichlids or gouramis.'),
 ('Nematobrycon palmeri', 'Emperor Tetra', 5.00, 80, 6, 23.0, 27.0, 6.0, 7.5, 3.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Males are territorial with each other in a gentle, display-only way, so keep one male to several females or a group large enough to spread it out. Calm, slower than most tetras, and a good match for a planted community.'),
 ('Metynnis argenteus', 'Silver Dollar', 15.00, 300, 5, 24.0, 28.0, 5.5, 7.5, 4.0, 18.0,
  'PEACEFUL', 'INTERMEDIATE', 'HERBIVORE', FALSE, 'FISH',
  'Sold at coin size, grows to the size of a saucer, and needs a group of five and a long tank to feel secure. It is a vegetarian: feed spirulina, blanched spinach or cucumber, and expect soft plants to vanish. Calm with other fish of its size; nervous and prone to jumping when kept alone. Lid required.'),
 ('Gasteropelecus sternicla', 'Silver Hatchetfish', 6.50, 100, 6, 24.0, 27.0, 5.5, 7.5, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Lives in the top few centimetres of the tank and can launch itself out of the water, so a fitted lid is not optional. Takes food from the surface -- floating flake, small insects, fruit flies. Peaceful and shy; keep a group of six with floating plants for cover and gentle current.'),
 ('Puntigrus tetrazona', 'Tiger Barb', 7.00, 100, 8, 22.0, 27.0, 6.0, 7.5, 4.0, 15.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Bold, hardy and always moving. In a group of eight it chases its own kind and leaves others alone; in threes it nips everything. Do not keep it with bettas, angelfish, gouramis or fancy goldfish. Green and albino tiger barbs are colour forms of the same species and school together.'),
 ('Puntius titteya', 'Cherry Barb', 5.00, 60, 6, 23.0, 27.0, 6.0, 7.5, 4.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'One of the few barbs that is genuinely peaceful, so it works in a gentle planted community with shrimp, rasboras and gouramis. Males colour up deep red; females stay orange-brown. The species is threatened in the wild and nearly every fish in the trade is farm-bred.'),
 ('Pethia conchonius', 'Rosy Barb', 10.00, 150, 6, 18.0, 25.0, 6.0, 8.0, 5.0, 20.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', FALSE, 'FISH',
  'An Indian fish -- wild populations live in the rivers and streams of North and North-East India. It prefers cooler water than most tropicals and is comfortable unheated through a North Indian winter, but a 32 C summer room is its limit. Grows to around 10 cm, loves to dig at plant roots, and can nip in a small group.'),
 ('Pethia padamya', 'Odessa Barb', 6.00, 80, 6, 20.0, 26.0, 6.5, 7.5, 5.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A Myanmar barb with striking males. More peaceful than tiger barbs but still active; best in a group with more females than males. Tolerates cooler water and a wide range of hardness.'),
 ('Pethia nigrofasciata', 'Black Ruby Barb', 6.00, 80, 6, 22.0, 26.0, 6.0, 7.5, 4.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A Sri Lankan barb whose males turn deep purple-black with a red face when happy and well-fed. Peaceful in a group, suited to a planted community tank with gentle flow.'),
 ('Sahyadria denisonii', 'Denison Barb', 15.00, 250, 6, 18.0, 25.0, 6.5, 7.8, 5.0, 20.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Endemic to the fast rivers of the Western Ghats in Kerala and Karnataka. It is listed Endangered by the IUCN, and collection for the aquarium trade is one of the reasons -- we sell captive-bred fish only. It grows to 15 cm, schools, and needs strong current, lots of oxygen and a long tank. Warm, still water is what kills it: in an Indian summer without cooling, run extra aeration and a fan across the surface.'),
 ('Barbonymus schwanefeldii', 'Tinfoil Barb', 35.00, 800, 5, 22.0, 28.0, 6.5, 7.5, 5.0, 15.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', FALSE, 'FISH',
  'Sold as a small silver fish with red fins; grows to the size of a dinner plate and needs a group. It is peaceful but will swallow any fish that fits in its mouth and eats plants. Realistically a fish for a 200 cm tank or a pond, not a community aquarium.'),
 ('Danio albolineatus', 'Pearl Danio', 6.00, 60, 6, 20.0, 26.0, 6.5, 7.5, 5.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Fast, surface-to-middle swimmer with an iridescent pink-blue sheen. Hardy, tolerant of unheated rooms outside the coldest months, and peaceful toward others. Needs a lid and swimming room.'),
 ('Devario aequipinnatus', 'Giant Danio', 10.00, 150, 6, 22.0, 26.0, 6.0, 7.5, 5.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Found wild in hill streams across India, Nepal and Sri Lanka. A fast, schooling fish for a long tank with current. Peaceful but so active it can stress shy tankmates. Good dither fish for mid-sized cichlids.'),
 ('Danio margaritatus', 'Celestial Pearl Danio', 2.50, 40, 8, 20.0, 25.0, 6.5, 7.5, 5.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Tiny, shy and spectacular in a densely planted tank. Prefers cooler water than most tropicals -- 22 to 24 C is ideal -- so in summer keep it in a shaded, well-ventilated spot. Needs very small food. Males spar constantly, harmlessly.'),
 ('Danio choprae', 'Glowlight Danio', 3.00, 40, 8, 20.0, 26.0, 6.5, 7.5, 5.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A small danio from northern Myanmar, closely related to the zebra. Bright orange and blue barring, very hardy, and happy in a smaller tank than most danios. Keep eight or more.'),
 ('Tanichthys albonubes', 'White Cloud Mountain Minnow', 4.00, 40, 6, 16.0, 24.0, 6.5, 8.0, 5.0, 20.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A small Chinese minnow that does best between 18 and 22 C. That makes it easy in a hill-station or a North Indian winter and difficult in a 32 C Chennai summer, so shade the tank and aerate well. Peaceful, schooling, and a good companion for goldfish-free cool tanks. The gold and long-fin forms are the same species.'),
 ('Rasbora trilineata', 'Scissortail Rasbora', 10.00, 150, 6, 22.0, 26.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Grows larger than the harlequin and needs swimming space. Peaceful, hardy, and good with gouramis, cichlids of similar size and larger tetras. A tight lid helps; it jumps when startled.'),
 ('Trigonostigma espei', 'Lambchop Rasbora', 3.00, 40, 8, 23.0, 28.0, 5.5, 7.0, 1.0, 10.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Similar to the harlequin rasbora but slimmer, with a lamb-chop-shaped black patch on a copper-orange body. Peaceful and shrimp-safe as adults. Best in soft water with plants and dim light.'),
 ('Poecilia sphenops', 'Molly', 10.00, 80, 3, 24.0, 28.0, 7.5, 8.5, 10.0, 25.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Aquarium mollies are a mix of several Poecilia species bred together for colour, so this profile covers the trade fish rather than one pure wild species. They want warm, hard, alkaline water -- which is what most Indian borewell and municipal water already is -- and they graze algae constantly. Keep more females than males. The "balloon" form is bred for a shortened, curved spine and tends to live a shorter life. Mollies breed readily, so plan for fry.'),
 ('Xiphophorus maculatus', 'Platy', 6.00, 60, 3, 20.0, 26.0, 7.0, 8.2, 10.0, 25.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Small, hardy and cheerful, and among the best fish for a childs first tank. Happy in hard water and a wide temperature range. Keep two or three females per male so no female is chased constantly. Expect fry every month in a mixed group.'),
 ('Xiphophorus hellerii', 'Swordtail', 12.00, 100, 3, 22.0, 28.0, 7.0, 8.2, 10.0, 25.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Larger and more active than the platy, with males carrying a sword extension on the lower tail. Males spar with each other, so keep one male or three-plus, with extra females. Hard, alkaline water suits it. Fast swimmers -- use a lid.'),
 ('Poecilia wingei', 'Endlers Livebearer', 3.00, 40, 3, 22.0, 28.0, 7.0, 8.2, 10.0, 25.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Males are tiny and covered in neon orange, green and black. Peaceful, hardy and prolific. Endlers and guppies interbreed freely, so if you want to keep either line pure, do not mix them in one tank.'),
 ('Trichogaster lalius', 'Dwarf Gourami', 9.00, 60, 1, 25.0, 28.0, 6.0, 7.5, 4.0, 15.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Wild populations live in the ponds and paddy canals of the Ganga and Brahmaputra plains, where it is known as lal kholisa. Males are territorial toward other males and are best kept one to a tank. Farmed dwarf gouramis worldwide carry a high rate of Dwarf Gourami Iridovirus, which has no cure, so we quarantine every batch and ask you to quarantine again at home. Floating plants help it feel secure.'),
 ('Trichogaster chuna', 'Honey Gourami', 5.00, 40, 1, 24.0, 28.0, 6.0, 7.5, 4.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Another fish of the Indian plains, from Bihar to Assam. Small, shy and peaceful enough for a nano community with rasboras and shrimp. Keep a pair or a male with two females. Males build bubble nests under floating leaves. Sturdier than the dwarf gourami.'),
 ('Trichopodus leerii', 'Pearl Gourami', 12.00, 150, 1, 24.0, 28.0, 6.0, 7.5, 2.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Covered in a white pearl mesh with a dark lateral line; males develop a vivid orange throat. Peaceful, slow and ideal as a centrepiece in a planted community. Needs access to the surface to breathe air, so leave a gap under the lid.'),
 ('Trichopodus trichopterus', 'Three Spot Gourami', 15.00, 150, 1, 22.0, 28.0, 6.0, 8.0, 5.0, 20.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'The blue, gold and opaline gouramis in the trade are all colour forms of this one fish. Easy and hardy, it grows to 15 cm, and older males can bully smaller or slower fish. Keep one male per tank with enough space and cover.'),
 ('Helostoma temminckii', 'Kissing Gourami', 20.00, 300, 1, 22.0, 28.0, 6.5, 8.0, 5.0, 20.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'OMNIVORE', FALSE, 'FISH',
  'The pink form is the one usually sold. Two kissing gouramis locking lips are testing each other for dominance. It grows large, rasps algae off every surface and will also eat soft plants. Needs a big tank and robust tankmates.'),
 ('Macropodus opercularis', 'Paradise Fish', 10.00, 80, 1, 16.0, 26.0, 6.0, 8.0, 5.0, 20.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'One of the first tropical fish ever kept in Europe, and still one of the toughest: it copes with unheated rooms and a wide range of water. Males are aggressive to each other and to other gouramis and bettas, so keep one male per tank with fast, robust companions.'),
 ('Sphaerichthys osphromenoides', 'Chocolate Gourami', 6.00, 60, 6, 25.0, 30.0, 4.0, 6.5, 1.0, 5.0,
  'PEACEFUL', 'ADVANCED', 'OMNIVORE', TRUE, 'FISH',
  'Needs soft, acidic, tea-coloured water with leaf litter and very stable conditions. Most Indian tap water is far too hard for it, so plan for RO or rainwater. Shy, slow and easily outcompeted at feeding time; keep it in a small group with tiny, calm tankmates only.'),
 ('Trichopsis pumila', 'Sparkling Gourami', 4.00, 30, 3, 24.0, 28.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'A tiny, peaceful gourami for a planted nano tank. Males produce audible clicks and croaks when displaying. Needs calm water, floating plants and small food. Keep a small group.'),
 ('Pterophyllum scalare', 'Freshwater Angelfish', 15.00, 200, 1, 24.0, 30.0, 6.0, 7.5, 3.0, 12.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Every colour form sold -- silver, black, marble, koi, platinum, veil-tail -- is the same species, bred for generations in farms. A full-grown angelfish is about 15 cm long and 20 cm tall, so tank height matters as much as volume. Adults will eat neon tetras and other fish small enough to swallow. Pairs become territorial when they spawn. Avoid fin-nippers like tiger barbs and serpae tetras.'),
 ('Symphysodon spp. (domestic strains)', 'Discus', 18.00, 300, 5, 28.0, 31.0, 5.5, 7.0, 1.0, 8.0,
  'PEACEFUL', 'ADVANCED', 'OMNIVORE', TRUE, 'FISH',
  'Domestic discus strains (red, blue diamond, pigeon blood, snakeskin, marlboro and many more) are bred from several wild Symphysodon species and forms, so this profile covers the domestic fish rather than one wild taxon. They need warm water around 29 C, soft water, and large, frequent water changes. Hard Indian borewell water must be blended with RO. Keep a group of five or more of similar size, feed high-protein food several times a day, and keep tankmates calm and heat-tolerant.'),
 ('Andinoacara pulcher', 'Blue Acara', 16.00, 200, 1, 20.0, 28.0, 6.5, 8.0, 5.0, 20.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Sturdier and calmer than most cichlids of its size and forgiving of a range of water. Digs a little and guards its fry fiercely when breeding, but is otherwise reasonable with similar-sized, non-aggressive tankmates. Small tetras will be eaten.'),
 ('Mikrogeophagus ramirezi', 'German Blue Ram', 7.00, 80, 1, 27.0, 30.0, 5.0, 7.0, 1.0, 8.0,
  'PEACEFUL', 'ADVANCED', 'OMNIVORE', TRUE, 'FISH',
  'One of the most beautiful dwarf cichlids and one of the most sensitive. Wants warm water (27-30 C), soft and slightly acidic, with no ammonia or nitrite at all. Add it only to a mature, stable tank. Electric blue, gold and balloon rams are forms of this species; balloon rams have a shortened spine. Keep a pair, not two males.'),
 ('Pelvicachromis pulcher', 'Kribensis', 10.00, 80, 1, 24.0, 28.0, 6.0, 7.5, 4.0, 15.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Easy, colourful and a good first cichlid. It needs a cave or flower pot, and a pair will breed and guard fry with real aggression during that time, so give tankmates room to get away. Tolerates a wider range of water than most dwarf cichlids. Albino form available.'),
 ('Apistogramma agassizii', 'Agassizs Dwarf Cichlid', 8.00, 60, 1, 24.0, 28.0, 5.0, 7.0, 1.0, 10.0,
  'TERRITORIAL', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'A small, colourful South American cichlid for a soft-water planted tank. Males are territorial and should be kept one per tank with several females, each with her own cave. Feed live or frozen foods. Colour peaks in soft, slightly acidic water.'),
 ('Apistogramma cacatuoides', 'Cockatoo Dwarf Cichlid', 9.00, 60, 1, 24.0, 28.0, 6.0, 7.5, 2.0, 15.0,
  'TERRITORIAL', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'The most adaptable Apistogramma, happy in slightly harder water than its relatives. Males display tall, spiky dorsal fins and orange-edged tails ("orange flash" and "double red" lines). One male per tank with two or three females and plenty of caves.'),
 ('Amatitlania nigrofasciata', 'Convict Cichlid', 12.00, 150, 1, 22.0, 28.0, 6.5, 8.0, 8.0, 20.0,
  'AGGRESSIVE', 'BEGINNER', 'OMNIVORE', FALSE, 'FISH',
  'Tough, small for a Central American cichlid, and will breed in almost any tank. When it does, it will fight fish several times its size. A pair needs its own tank or a big one with robust tankmates. Pink convicts are the same species.'),
 ('Thorichthys meeki', 'Firemouth Cichlid', 15.00, 150, 1, 24.0, 28.0, 6.5, 8.0, 8.0, 20.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'One of the calmer Central American cichlids: it would rather display its red throat than fight. Digs in sand, so root plants firmly. Good with other medium-sized fish; will eat small tetras.'),
 ('Rocio octofasciata', 'Jack Dempsey', 25.00, 300, 1, 22.0, 28.0, 6.5, 8.0, 8.0, 20.0,
  'AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', FALSE, 'FISH',
  'Named after a 1920s heavyweight boxer, and aggressive enough to deserve it once mature. Needs a large tank with caves and tankmates of equal size and toughness. The "Electric Blue Jack Dempsey" is a colour mutation that is smaller, calmer and more delicate than the wild-type fish.'),
 ('Hybrid (blood parrot cichlid)', 'Blood Parrot', 20.00, 200, 1, 24.0, 28.0, 6.5, 7.5, 5.0, 15.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'This is not a species. The blood parrot is a hybrid produced in Asian farms from Central American cichlids; the exact cross is not published. Its mouth cannot close fully, so it needs sinking pellets small enough to take easily. Usually peaceful and sociable for a cichlid. Avoid fish that have been dyed or tattooed with patterns or hearts -- the colour fades and the process harms the fish.'),
 ('Parachromis managuensis', 'Jaguar Cichlid', 55.00, 800, 1, 24.0, 28.0, 7.0, 8.0, 8.0, 20.0,
  'AGGRESSIVE', 'ADVANCED', 'CARNIVORE', FALSE, 'FISH',
  'A large predatory cichlid with a spotted, jaguar-like pattern. It will eat any fish it can swallow and fight anything it cannot. Adults need a tank of 800 litres or more and very strong filtration. Not a community fish at any size.'),
 ('Maylandia lombardoi', 'Kenyi Cichlid', 13.00, 300, 6, 24.0, 28.0, 7.8, 8.6, 10.0, 20.0,
  'AGGRESSIVE', 'INTERMEDIATE', 'HERBIVORE', FALSE, 'FISH',
  'An unusual mbuna where the adult male is yellow and the female blue -- the reverse of what most people expect. Very aggressive: keep it in a crowded, rocky mbuna tank with one male to several females. Herbivore -- avoid high-protein food.'),
 ('Pseudotropheus crabro', 'Bumblebee Cichlid', 16.00, 400, 6, 24.0, 28.0, 7.8, 8.6, 10.0, 20.0,
  'AGGRESSIVE', 'INTERMEDIATE', 'OMNIVORE', FALSE, 'FISH',
  'In the lake it cleans parasites off catfish and then steals their eggs. In the tank it is a large, aggressive mbuna that needs space, rockwork and other robust Malawi cichlids.'),
 ('Maylandia callainos', 'Cobalt Blue Zebra', 12.00, 300, 6, 24.0, 28.0, 7.8, 8.6, 10.0, 20.0,
  'AGGRESSIVE', 'INTERMEDIATE', 'HERBIVORE', FALSE, 'FISH',
  'A bright, bar-less blue mbuna. Typical mbuna behaviour: territorial, best kept overstocked with plenty of rocks to break up sight lines, and fed a vegetable-based diet. White and "cobalt ice" forms are the same fish.'),
 ('Nimbochromis venustus', 'Venustus', 25.00, 500, 4, 24.0, 28.0, 7.8, 8.6, 10.0, 20.0,
  'AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', FALSE, 'FISH',
  'In the lake it lies on the sand pretending to be dead, then eats the small fish that come to inspect it. In a tank it is a large hap that needs a long tank, open sand and tankmates too big to eat. Males turn blue-headed with age.'),
 ('Copadichromis borleyi', 'Yellowfin Borleyi', 16.00, 400, 4, 24.0, 28.0, 7.8, 8.6, 10.0, 20.0,
  'PEACEFUL', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'One of the calmer Malawi haps, feeding on plankton in open water. Keep with peacocks and other gentle haps, not with aggressive mbuna, which will bully it. One male to several females.'),
 ('Cyphotilapia frontosa', 'Frontosa', 33.00, 600, 4, 24.0, 27.0, 7.8, 9.0, 10.0, 20.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'Grows slowly to about 30 cm and lives 20 years or more. Calm for a cichlid but will eat any fish that fits in its mouth -- including small Tanganyika cichlids. Keep a group with one male in a large tank with hard, alkaline water and very stable conditions.'),
 ('Neolamprologus leleupi', 'Lemon Cichlid', 10.00, 100, 1, 24.0, 27.0, 7.8, 9.0, 10.0, 20.0,
  'TERRITORIAL', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'Small and very colourful, but territorial around its cave. Keep one pair, with plenty of rockwork and caves. Feed meaty foods -- colour fades on a flake-only diet. Hard, alkaline water is essential.'),
 ('Neolamprologus brichardi', 'Brichardi', 10.00, 100, 1, 24.0, 27.0, 7.8, 9.0, 10.0, 20.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'One pair grows into a colony: older young stay and guard newer broods. The colony defends its rockwork fiercely, so plan the tank around it. The albino form is the same species.'),
 ('Lamprologus ocellatus', 'Ocellatus Shell Dweller', 5.00, 40, 1, 24.0, 27.0, 7.8, 9.0, 10.0, 20.0,
  'TERRITORIAL', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'Lives and breeds inside empty snail shells, so provide one or two per fish. Small but bold -- it will defend its shell against much bigger fish. A pair or trio fits a 40-litre tank with a sand bottom. Needs hard, alkaline water.'),
 ('Corydoras paleatus', 'Peppered Cory', 7.00, 60, 6, 18.0, 25.0, 6.0, 8.0, 5.0, 19.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Comes from the cooler south of South America and prefers lower temperatures than most tropicals. It suits a winter tank or an air-conditioned room better than a 30 C summer tank. Like all corydoras it needs a group and soft sand for its barbels.'),
 ('Corydoras trilineatus', 'Julii Cory', 6.00, 60, 6, 22.0, 26.0, 6.0, 7.5, 2.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'The fish sold as "julii cory" is almost always Corydoras trilineatus, which has finer spots and a stripe along the side. The true C. julii is rarely exported. Peaceful and busy; keep a group on sand.'),
 ('Corydoras arcuatus', 'Skunk Cory', 5.00, 60, 6, 22.0, 26.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'A striking, peaceful cory that is slightly more sensitive to poor water than bronze or peppered corys. Keep a group on fine sand in a mature tank.'),
 ('Corydoras splendens', 'Emerald Green Cory', 7.50, 80, 6, 22.0, 28.0, 6.0, 7.8, 2.0, 20.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Larger than most corydoras and more tolerant of warm water, which makes it a good choice where summer tanks run above 28 C. Peaceful, keep a group on sand.'),
 ('Kryptopterus vitreolus', 'Glass Catfish', 8.00, 100, 6, 24.0, 28.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'A transparent, shoaling catfish that hovers mid-water in a group. Alone or in pairs it hides and stops eating. Needs a calm tank without boisterous fish, and small meaty foods.'),
 ('Pimelodus pictus', 'Pictus Catfish', 12.00, 250, 3, 22.0, 27.0, 6.0, 7.5, 2.0, 15.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', FALSE, 'FISH',
  'A restless, spotted catfish that needs a long tank and a group of its own kind. It eats any fish small enough to swallow, usually at night. The fin spines lock into nets, so catch it with a container.'),
 ('Synodontis nigriventris', 'Upside-Down Catfish', 10.00, 100, 3, 22.0, 28.0, 6.0, 7.5, 4.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Spends much of its time belly-up under leaves and driftwood -- its belly is even darker than its back to match. Peaceful, sociable, and best in a small group with caves.'),
 ('Platydoras armatulus', 'Striped Raphael Catfish', 22.00, 250, 1, 23.0, 29.0, 6.0, 7.5, 4.0, 18.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'A tough, long-lived catfish that hides by day and scavenges at night. Peaceful but will swallow very small fish. It makes a grunting sound with its fin spines. Use a container, not a net.'),
 ('Baryancistrus xanthellus', 'Gold Nugget Pleco', 22.00, 300, 1, 26.0, 30.0, 6.0, 7.5, 2.0, 12.0,
  'TERRITORIAL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'A strikingly patterned pleco from the Xingu river in Brazil. Needs warm, well-oxygenated water, strong flow and caves. Territorial toward other plecos. Feed a mix of vegetable and meaty sinking foods.'),
 ('Panaque nigrolineatus', 'Royal Pleco', 43.00, 600, 1, 22.0, 28.0, 6.5, 7.5, 2.0, 15.0,
  'TERRITORIAL', 'ADVANCED', 'HERBIVORE', TRUE, 'FISH',
  'A large pleco that rasps and digests wood, so driftwood is essential. It produces a lot of waste and needs big filtration. Territorial with other plecos. A long-term fish for a very large tank.'),
 ('Hypancistrus inspector', 'Snowball Pleco', 16.00, 150, 1, 24.0, 28.0, 6.0, 7.5, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'A peaceful, night-active pleco that eats more meaty food than algae -- feed sinking pellets and frozen food, not just wafers. Needs caves and clean, oxygen-rich water.'),
 ('Chromobotia macracanthus', 'Clown Loach', 30.00, 400, 5, 25.0, 30.0, 6.0, 7.5, 5.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Orange with three black bands, playful and very social -- one alone is a stressed fish. They are sold small but can live 20 years and grow to 30 cm. Loves warmth, eats snails, and is prone to white spot, so quarantine carefully.'),
 ('Botia almorhae', 'Yoyo Loach', 15.00, 150, 5, 24.0, 28.0, 6.0, 7.5, 5.0, 12.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Found wild in northern India and Nepal and sold for decades as the lohachata loach. Active, noisy (it clicks) and a good snail eater. Needs a group of five or more and caves, or it becomes a bully.'),
 ('Botia striata', 'Zebra Loach', 9.00, 100, 5, 23.0, 26.0, 6.0, 7.5, 5.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Endemic to the Western Ghats of Maharashtra and Karnataka and threatened in the wild. One of the smaller and calmer botias, it suits a community tank with a sandy bottom and caves. Keep a group.'),
 ('Ambastaia sidthimunki', 'Dwarf Chain Loach', 6.00, 80, 6, 24.0, 28.0, 6.0, 7.5, 5.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Unusually for a loach, it swims up in open water with its group. Peaceful and small enough for a community tank, and it eats small snails. Almost gone from the wild; the trade relies on farm-bred fish.'),
 ('Sewellia lineolata', 'Reticulated Hillstream Loach', 6.00, 80, 3, 20.0, 24.0, 6.5, 7.5, 5.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'HERBIVORE', TRUE, 'FISH',
  'Built like a tiny stingray to cling to rocks in fast streams. It needs strong current, lots of oxygen and cool water. An Indian summer without cooling is hard on it. Grazes algae and biofilm from smooth stones.'),
 ('Epalzeorhynchos frenatum', 'Rainbow Shark', 15.00, 200, 1, 22.0, 27.0, 6.5, 7.5, 5.0, 15.0,
  'TERRITORIAL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Not a shark -- a cyprinid with a shark-like fin. Territorial toward its own kind and similar-looking fish, so keep one per tank. Fine with fast mid-water fish.'),
 ('Epalzeorhynchos bicolor', 'Red Tail Shark', 15.00, 200, 1, 22.0, 27.0, 6.5, 7.5, 5.0, 15.0,
  'TERRITORIAL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Extinct or nearly so in its native Thai river; the trade is farm-bred. More aggressive than the rainbow shark as it ages. One per tank, with caves.'),
 ('Balantiocheilos melanopterus', 'Bala Shark', 35.00, 800, 5, 22.0, 28.0, 6.5, 7.5, 5.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'A peaceful, silver, black-edged schooling fish that grows far larger than its shop size suggests. Needs a group and a tank of 200 cm or more. Jumps -- use a lid.'),
 ('Crossocheilus oblongus', 'Siamese Algae Eater', 15.00, 150, 3, 24.0, 26.0, 6.5, 7.5, 5.0, 12.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'The best algae eater for planted tanks, and one of very few fish that eat black beard algae. A black stripe runs from the nose into the tail fin. Shops often mislabel the Chinese algae eater or the "flying fox" as this fish.'),
 ('Gyrinocheilus aymonieri', 'Chinese Algae Eater', 28.00, 250, 1, 22.0, 28.0, 6.0, 8.0, 5.0, 19.0,
  'SEMI_AGGRESSIVE', 'BEGINNER', 'HERBIVORE', TRUE, 'FISH',
  'Eats algae well when small, but grows to 28 cm and older fish often attach to the sides of slow, flat-bodied fish such as angelfish and discus. Better in a tank of fast, robust fish.'),
 ('Carassius auratus', 'Goldfish', 20.00, 150, 1, 18.0, 24.0, 7.0, 8.0, 5.0, 19.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', FALSE, 'FISH',
  'Goldfish are cool-water fish -- above about 26 C they need extra aeration. Fancy goldfish (orandas, ryukins, moors, ranchus, pearlscales) grow to about 20 cm and need 75-100 litres each, much more than the round bowls often sold with them. Single-tail goldfish such as comets grow to 30 cm and are pond fish. Goldfish produce a lot of waste. Keep them only with other goldfish -- tropical fish want warmer water, and fin-nippers damage fancy goldfish fins.'),
 ('Melanotaenia boesemani', 'Boesemani Rainbowfish', 10.00, 200, 6, 27.0, 30.0, 7.0, 8.0, 10.0, 20.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'Juveniles look plain; adult males become half blue, half orange. Wild populations are protected in their one lake in West Papua, so the trade is farm-bred. Active, peaceful and hard-water tolerant. Keep a group with more females than males.'),
 ('Glossolepis incisus', 'Red Irian Rainbowfish', 15.00, 250, 6, 22.0, 26.0, 7.0, 8.0, 9.0, 19.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Males develop a tall back and solid salmon-red colour with age. Active and peaceful but needs a lot of swimming space. Happy in hard, alkaline water.'),
 ('Iriatherina werneri', 'Threadfin Rainbowfish', 5.00, 60, 6, 24.0, 30.0, 5.5, 7.5, 2.0, 12.0,
  'PEACEFUL', 'INTERMEDIATE', 'OMNIVORE', TRUE, 'FISH',
  'Males grow extraordinary thread-like fin extensions. Slow and delicate; fin-nippers or fast feeders will outcompete and damage it. Best in a calm planted tank with small food.'),
 ('Melanotaenia praecox', 'Dwarf Neon Rainbowfish', 6.00, 100, 6, 24.0, 28.0, 6.0, 8.0, 5.0, 15.0,
  'PEACEFUL', 'BEGINNER', 'OMNIVORE', TRUE, 'FISH',
  'One of the smallest and easiest rainbowfish -- neon blue with red or yellow fins. Peaceful and schooling, and suits a medium community tank.'),
 ('Carinotetraodon travancoricus', 'Pea Puffer', 3.50, 40, 1, 24.0, 28.0, 7.0, 8.0, 5.0, 15.0,
  'AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'A true freshwater puffer endemic to rivers in Kerala and southern Karnataka, now listed Vulnerable because of overcollection. It eats snails, bloodworms and other live or frozen food -- not flake or pellets. It nips fins, so keep it in a species tank, around 20 litres per fish, with dense plants to break lines of sight.'),
 ('Apteronotus albifrons', 'Black Ghost Knifefish', 50.00, 500, 1, 23.0, 28.0, 6.0, 8.0, 2.0, 15.0,
  'SEMI_AGGRESSIVE', 'ADVANCED', 'CARNIVORE', TRUE, 'FISH',
  'A velvet-black fish that swims forward and backward using a long fin under its belly. It hunts by electric sense at night, so it needs a hiding tube and will eat small fish. Sensitive to poor water quality. Grows large and lives more than 10 years.'),
 ('Mastacembelus erythrotaenia', 'Fire Eel', 100.00, 800, 1, 24.0, 28.0, 6.0, 7.5, 5.0, 15.0,
  'SEMI_AGGRESSIVE', 'ADVANCED', 'CARNIVORE', TRUE, 'FISH',
  'Not a true eel. It needs soft sand to bury in, a tight-fitting lid and a very large tank as an adult. Eats worms and meaty food and will take small fish. Skin is sensitive to medications and rough gravel.'),
 ('Mastacembelus armatus', 'Tire Track Eel', 75.00, 600, 1, 22.0, 28.0, 6.5, 7.5, 5.0, 15.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'Found in rivers and ponds across India, where it is also a food fish. In aquaria it grows to 60-75 cm, buries in sand and is an expert escape artist. Eats worms, prawns and small fish. Needs a sandy bottom and a secure lid.'),
 ('Polypterus ornatipinnis', 'Ornate Bichir', 60.00, 700, 1, 25.0, 28.0, 6.5, 7.5, 5.0, 15.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'Breathes air as well as through its gills, so it needs access to the surface. A night hunter that eats any fish small enough to swallow. Needs a large tank with a sealed lid -- it climbs out through small gaps.'),
 ('Pantodon buchholzi', 'African Butterflyfish', 12.00, 150, 1, 25.0, 30.0, 6.0, 7.5, 1.0, 10.0,
  'SEMI_AGGRESSIVE', 'INTERMEDIATE', 'CARNIVORE', TRUE, 'FISH',
  'Waits at the surface for insects and can jump well above the water line, so a lid is essential. Feed floating insects, crickets and frozen food. Keep with mid- and bottom-dwellers that are too big to eat.');

-- ============================================================= products ==

INSERT INTO product
 (sku, slug, name, summary, price_minor, currency, is_livestock, category_id, species_profile_id, image_key)
SELECT v.sku, v.slug, v.name, v.summary, v.price_minor, 'INR', TRUE,
       (SELECT id FROM category        WHERE slug            = v.category),
       (SELECT id FROM species_profile WHERE scientific_name = v.scientific_name),
       NULL
  FROM (VALUES
    ('FSH-TET-03', 'black-skirt-tetra', 'Black Skirt Tetra',
     'Tank-bred. Hardy, cheap and forgiving of Indian tap water -- but a fin-nipper in a small group. Buy six or more.',
     4000, 'tetras', 'Gymnocorymbus ternetzi'),
    ('FSH-TET-04', 'serpae-tetra', 'Serpae Tetra',
     'Tank-bred. Blood-red and never still. A known fin-nipper -- keep eight or more, and no long-finned tankmates.',
     5000, 'tetras', 'Hyphessobrycon eques'),
    ('FSH-TET-05', 'rummynose-tetra', 'Rummy Nose Tetra',
     'Tank-bred. The tightest-schooling tetra in the shop. Its red nose fades when the water is wrong -- a free water test.',
     12000, 'tetras', 'Hemigrammus bleheri'),
    ('FSH-TET-06', 'glowlight-tetra', 'Glowlight Tetra',
     'Tank-bred. A glowing orange line on a clear body. Peaceful, easy, and at its best in a dim planted tank.',
     5000, 'tetras', 'Hemigrammus erythrozonus'),
    ('FSH-TET-07', 'black-neon-tetra', 'Black Neon Tetra',
     'Tank-bred. Not a neon at all, and hardier than one. A white-and-black stripe that reads well against green plants.',
     4500, 'tetras', 'Hyphessobrycon herbertaxelrodi'),
    ('FSH-TET-08', 'diamond-tetra', 'Diamond Tetra',
     'Tank-bred. Scales that sparkle like glitter as it turns. Males grow long, flowing fins with age.',
     9000, 'tetras', 'Moenkhausia pittieri'),
    ('FSH-TET-09', 'ember-tetra', 'Ember Tetra',
     'Tank-bred. Two centimetres of orange. Made for nano tanks and planted tanks, and safe with shrimp.',
     6000, 'tetras', 'Hyphessobrycon amandae'),
    ('FSH-TET-10', 'congo-tetra', 'Congo Tetra',
     'Tank-bred. An African tetra with rainbow scales and feathery fins. Large, calm, and needs a big tank.',
     25000, 'tetras', 'Phenacogrammus interruptus'),
    ('FSH-TET-11', 'bleeding-heart-tetra', 'Bleeding Heart Tetra',
     'Tank-bred. A deep-bodied tetra with a red "heart" spot. Calm, and stunning in a blackwater setup.',
     12000, 'tetras', 'Hyphessobrycon erythrostigma'),
    ('FSH-TET-12', 'buenos-aires-tetra', 'Buenos Aires Tetra',
     'Tank-bred. Nearly indestructible and fine without a heater in most of India -- but it eats plants.',
     5000, 'tetras', 'Hyphessobrycon anisitsi'),
    ('FSH-TET-13', 'penguin-tetra', 'Penguin Tetra',
     'Tank-bred. Swims tail-down at an angle, with a black stripe running into the lower tail lobe.',
     5000, 'tetras', 'Thayeria boehlkei'),
    ('FSH-TET-14', 'x-ray-tetra', 'X-Ray Tetra',
     'Tank-bred. A see-through body and yellow-black-white dorsal fin. One of the most adaptable tetras there is.',
     5000, 'tetras', 'Pristella maxillaris'),
    ('FSH-TET-15', 'head-and-tail-light-tetra', 'Head and Tail Light Tetra',
     'Tank-bred. Two glowing spots, one at the eye and one at the tail. An inexpensive, hardy classic.',
     4000, 'tetras', 'Hemigrammus ocellifer'),
    ('FSH-TET-16', 'black-phantom-tetra', 'Black Phantom Tetra',
     'Tank-bred. Smoky silver with a black shoulder patch. Males spar with flared fins but never hurt each other.',
     8000, 'tetras', 'Hyphessobrycon megalopterus'),
    ('FSH-TET-17', 'red-eye-tetra', 'Red Eye Tetra',
     'Tank-bred. Silver scales, black tail band and a red ring around the eye. Very hardy.',
     5000, 'tetras', 'Moenkhausia sanctaefilomenae'),
    ('FSH-TET-18', 'emperor-tetra', 'Emperor Tetra',
     'Tank-bred. Purple-blue body, pitchfork tail and a turquoise eye on the male.',
     15000, 'tetras', 'Nematobrycon palmeri'),
    ('FSH-TET-19', 'silver-dollar', 'Silver Dollar',
     'Tank-bred. A peaceful, plate-shaped relative of the pacu. Grows to 15 cm and eats every plant you own.',
     15000, 'tetras', 'Metynnis argenteus'),
    ('FSH-TET-20', 'silver-hatchetfish', 'Silver Hatchetfish',
     'Wild-type. A surface-dwelling fish with a keel-shaped chest, built for gliding. Needs a tight lid.',
     12000, 'tetras', 'Gasteropelecus sternicla'),
    ('FSH-BRB-01', 'tiger-barb', 'Tiger Barb',
     'Tank-bred. The classic striped barb. Green and albino forms are the same fish. Keep eight or more.',
     5000, 'barbs', 'Puntigrus tetrazona'),
    ('FSH-BRB-02', 'cherry-barb', 'Cherry Barb',
     'Tank-bred. A small, peaceful barb from Sri Lanka. Males turn cherry red when they display.',
     6000, 'barbs', 'Puntius titteya'),
    ('FSH-BRB-03', 'rosy-barb', 'Rosy Barb',
     'Tank-bred. A native of North Indian rivers, happy in cool water and very hardy. Grows bigger than you think.',
     4000, 'barbs', 'Pethia conchonius'),
    ('FSH-BRB-04', 'odessa-barb', 'Odessa Barb',
     'Tank-bred. Males carry a scarlet band over black-edged scales. Calm for a barb.',
     6000, 'barbs', 'Pethia padamya'),
    ('FSH-BRB-05', 'black-ruby-barb', 'Black Ruby Barb',
     'Tank-bred. Males flush ruby-red on the head over black bands when they are in condition.',
     7000, 'barbs', 'Pethia nigrofasciata'),
    ('FSH-BRB-06', 'denison-barb', 'Denison Barb (Miss Kerala)',
     'Captive-bred only. Keralas own river barb -- endangered in the wild. Needs cool, fast, clean water and a long tank.',
     35000, 'barbs', 'Sahyadria denisonii'),
    ('FSH-BRB-07', 'tinfoil-barb', 'Tinfoil Barb',
     'Sold at 5 cm. Reaches 35 cm. A shoal of these needs a tank most homes do not have -- please check the size first.',
     8000, 'barbs', 'Barbonymus schwanefeldii'),
    ('FSH-DAN-01', 'pearl-danio', 'Pearl Danio',
     'Tank-bred. A shimmering, pearly danio -- fast, hardy and good in cooler tanks.',
     5000, 'barbs', 'Danio albolineatus'),
    ('FSH-DAN-02', 'giant-danio', 'Giant Danio',
     'Tank-bred. An Indian native from the Western Ghats and the North-East. Blue-and-gold stripes, 10 cm, very active.',
     6000, 'barbs', 'Devario aequipinnatus'),
    ('FSH-DAN-03', 'celestial-pearl-danio', 'Celestial Pearl Danio (Galaxy Rasbora)',
     'Tank-bred. Dark blue with gold spots and orange fins. A nano fish for a cool, planted tank.',
     15000, 'barbs', 'Danio margaritatus'),
    ('FSH-DAN-04', 'glowlight-danio', 'Glowlight Danio',
     'Tank-bred. A tiny danio with orange-and-blue bars. Hardy, active and nano-friendly.',
     12000, 'barbs', 'Danio choprae'),
    ('FSH-DAN-05', 'white-cloud-minnow', 'White Cloud Mountain Minnow',
     'Tank-bred. The classic unheated-tank fish. Hardy -- but it is a cool-water fish and a hot summer is hard on it.',
     3000, 'barbs', 'Tanichthys albonubes'),
    ('FSH-RAS-02', 'scissortail-rasbora', 'Scissortail Rasbora',
     'Tank-bred. Black-and-white tail tips that flick like scissors. A calm, larger rasbora for an open tank.',
     6000, 'barbs', 'Rasbora trilineata'),
    ('FSH-RAS-03', 'lambchop-rasbora', 'Lambchop Rasbora',
     'Tank-bred. The harlequins smaller, more orange cousin. For nano and planted tanks.',
     8000, 'barbs', 'Trigonostigma espei'),
    ('FSH-LIV-02', 'molly-assorted', 'Molly, Assorted (Black, Dalmatian, Gold Dust)',
     'Tank-bred. Colours vary. A hard-water fish that likes Indias hard tap water better than most tropicals.',
     4000, 'livebearers', 'Poecilia sphenops'),
    ('FSH-LIV-03', 'platy-assorted', 'Platy, Assorted (Red, Mickey Mouse, Wag, Sunset)',
     'Tank-bred. Colours vary. The easiest livebearer there is, and it breeds without any help.',
     3000, 'livebearers', 'Xiphophorus maculatus'),
    ('FSH-LIV-04', 'swordtail-assorted', 'Swordtail, Assorted',
     'Tank-bred. Males grow a long sword on the tail. Red, black, pineapple and hi-fin forms available.',
     5000, 'livebearers', 'Xiphophorus hellerii'),
    ('FSH-LIV-05', 'endlers-livebearer', 'Endlers Livebearer',
     'Tank-bred. A smaller, wilder-looking relative of the guppy with neon colours. Nano and shrimp tank friendly.',
     6000, 'livebearers', 'Poecilia wingei'),
    ('FSH-GOU-01', 'dwarf-gourami', 'Dwarf Gourami (Lal Kholisa)',
     'Tank-bred. A native of West Bengal and Assam. Flame, powder blue and neon forms available. One male per tank.',
     8000, 'anabantoids', 'Trichogaster lalius'),
    ('FSH-GOU-02', 'honey-gourami', 'Honey Gourami (Chuna Kholisa)',
     'Tank-bred. An Indian native and the gentlest gourami. Males turn honey-gold with a black throat when breeding.',
     8000, 'anabantoids', 'Trichogaster chuna'),
    ('FSH-GOU-03', 'pearl-gourami', 'Pearl Gourami',
     'Tank-bred. Lace-patterned and graceful, and one of the calmest large gouramis. Males show an orange breast.',
     12000, 'anabantoids', 'Trichopodus leerii'),
    ('FSH-GOU-04', 'three-spot-gourami', 'Three Spot Gourami (Blue / Gold / Opaline)',
     'Tank-bred. Blue, gold and opaline are one species. Very hardy; males can turn bossy as they grow.',
     6000, 'anabantoids', 'Trichopodus trichopterus'),
    ('FSH-GOU-05', 'kissing-gourami', 'Kissing Gourami',
     'Tank-bred. The "kissing" is a mouth-to-mouth shoving contest, not affection. Grows to 20 cm or more.',
     8000, 'anabantoids', 'Helostoma temminckii'),
    ('FSH-GOU-06', 'paradise-fish', 'Paradise Fish',
     'Tank-bred. The original aquarium fish -- blue and red bars and long fins. Tough, but males fight.',
     6000, 'anabantoids', 'Macropodus opercularis'),
    ('FSH-GOU-07', 'chocolate-gourami', 'Chocolate Gourami',
     'Wild-type. A delicate blackwater mouthbrooder for soft, acidic, very clean water. Not a beginner fish.',
     25000, 'anabantoids', 'Sphaerichthys osphromenoides'),
    ('FSH-GOU-08', 'sparkling-gourami', 'Sparkling Gourami',
     'Tank-bred. A 4 cm gourami with blue-sparkled fins and red-edged eyes. Males make a croaking sound.',
     10000, 'anabantoids', 'Trichopsis pumila'),
    ('FSH-SAM-04', 'angelfish', 'Freshwater Angelfish, Assorted',
     'Tank-bred. Colours vary (silver, black, koi, marble, gold). Grows 20 cm tall -- choose a tall tank. Eats neons.',
     15000, 'cichlids-south-american', 'Pterophyllum scalare'),
    ('FSH-SAM-05', 'discus', 'Discus, Assorted Strains',
     'Tank-bred. The king of the aquarium -- and the most demanding fish on this page. Warm, soft, very clean water only.',
     150000, 'cichlids-south-american', 'Symphysodon spp. (domestic strains)'),
    ('FSH-SAM-06', 'blue-acara', 'Blue Acara',
     'Tank-bred. A hardy, electric-blue cichlid. A good first cichlid.',
     15000, 'cichlids-south-american', 'Andinoacara pulcher'),
    ('FSH-DWC-01', 'german-blue-ram', 'German Blue Ram',
     'Tank-bred. Electric blue, gold and balloon forms available. Needs hot, soft, very clean water.',
     25000, 'cichlids-dwarf', 'Mikrogeophagus ramirezi'),
    ('FSH-DWC-02', 'kribensis', 'Kribensis',
     'Tank-bred. A hardy West African dwarf cichlid with a pink belly. Pairs breed easily in a cave.',
     20000, 'cichlids-dwarf', 'Pelvicachromis pulcher'),
    ('FSH-DWC-03', 'apistogramma-agassizii', 'Agassizs Dwarf Cichlid',
     'Tank-bred. Flame red, double red and gold forms. One male with two or three females, and a cave each.',
     35000, 'cichlids-dwarf', 'Apistogramma agassizii'),
    ('FSH-DWC-04', 'cockatoo-cichlid', 'Cockatoo Dwarf Cichlid',
     'Tank-bred. The males dorsal fin rises like a cockatoos crest. Hardier than most Apistogramma.',
     30000, 'cichlids-dwarf', 'Apistogramma cacatuoides'),
    ('FSH-CAM-06', 'convict-cichlid', 'Convict Cichlid',
     'Tank-bred. Black bars (or pink, in the albino form). The easiest cichlid to breed -- and a fierce parent.',
     8000, 'cichlids-central-american', 'Amatitlania nigrofasciata'),
    ('FSH-CAM-07', 'firemouth-cichlid', 'Firemouth Cichlid',
     'Tank-bred. Flares a fiery red throat to warn off rivals. More bluff than bite for a Central American.',
     15000, 'cichlids-central-american', 'Thorichthys meeki'),
    ('FSH-CAM-08', 'jack-dempsey', 'Jack Dempsey',
     'Tank-bred. Dark body covered in blue-green spangles. Grows to 25 cm and earns its boxers name.',
     30000, 'cichlids-central-american', 'Rocio octofasciata'),
    ('FSH-CAM-09', 'blood-parrot', 'Blood Parrot',
     'Tank-bred. A man-made hybrid, not a species. Round body, beak-like mouth, bright orange colour.',
     30000, 'cichlids-central-american', 'Hybrid (blood parrot cichlid)'),
    ('FSH-CAM-10', 'jaguar-cichlid', 'Jaguar Cichlid (Managuense)',
     'Sold at 7 cm. Reaches 55 cm. A predator for a very large, species-only tank.',
     40000, 'cichlids-central-american', 'Parachromis managuensis'),
    ('FSH-MAL-11', 'kenyi-cichlid', 'Kenyi Cichlid',
     'Tank-bred. Females and juveniles are blue with black bars; males turn yellow. One of the meanest mbuna.',
     15000, 'malawi', 'Maylandia lombardoi'),
    ('FSH-MAL-12', 'bumblebee-cichlid', 'Bumblebee Cichlid',
     'Tank-bred. Yellow and black bars, and it can turn nearly black in seconds. Larger and tougher than most mbuna.',
     20000, 'malawi', 'Pseudotropheus crabro'),
    ('FSH-MAL-13', 'cobalt-blue-zebra', 'Cobalt Blue Zebra',
     'Tank-bred. Solid powder-blue, with no bars. A classic mbuna.',
     15000, 'malawi', 'Maylandia callainos'),
    ('FSH-MAL-14', 'venustus', 'Venustus (Giraffe Cichlid)',
     'Tank-bred. A giraffe-patterned ambush predator from Lake Malawi. Grows to 25 cm.',
     40000, 'malawi', 'Nimbochromis venustus'),
    ('FSH-MAL-15', 'yellowfin-borleyi', 'Yellowfin Borleyi',
     'Tank-bred. A peaceful open-water hap -- males show red or yellow fins against a blue head.',
     45000, 'malawi', 'Copadichromis borleyi'),
    ('FSH-TNG-01', 'frontosa', 'Frontosa',
     'Tank-bred. A slow, majestic, blue-and-white banded cichlid with a head hump. Long-lived and large.',
     120000, 'tanganyika', 'Cyphotilapia frontosa'),
    ('FSH-TNG-02', 'lemon-cichlid', 'Lemon Cichlid (Leleupi)',
     'Tank-bred. Bright lemon-to-orange all over. A small but feisty cave-dweller.',
     35000, 'tanganyika', 'Neolamprologus leleupi'),
    ('FSH-TNG-03', 'brichardi', 'Brichardi (Princess of Burundi)',
     'Tank-bred. Elegant lyre-tailed cichlid that lives in family colonies. Older siblings help raise the young.',
     25000, 'tanganyika', 'Neolamprologus brichardi'),
    ('FSH-TNG-04', 'ocellatus', 'Ocellatus Shell Dweller',
     'Tank-bred. A 5 cm cichlid that lives in empty snail shells. Gold form available.',
     35000, 'tanganyika', 'Lamprologus ocellatus'),
    ('FSH-COR-06', 'peppered-cory', 'Peppered Cory',
     'Tank-bred. A cool-water cory. Hardy -- but not for a hot tank. Keep six on sand.',
     8000, 'catfish-corydoras', 'Corydoras paleatus'),
    ('FSH-COR-07', 'false-julii-cory', 'Julii Cory (False Julii)',
     'Tank-bred. A leopard-spotted cory. Almost every "julii" in the trade is really this species.',
     15000, 'catfish-corydoras', 'Corydoras trilineatus'),
    ('FSH-COR-08', 'skunk-cory', 'Skunk Cory',
     'Tank-bred. A pale cory with a black stripe arching from nose to tail.',
     18000, 'catfish-corydoras', 'Corydoras arcuatus'),
    ('FSH-COR-09', 'emerald-green-cory', 'Emerald Green Cory',
     'Tank-bred. A large, metallic-green cory that takes Indias summer heat better than most.',
     20000, 'catfish-corydoras', 'Corydoras splendens'),
    ('FSH-CAT-01', 'glass-catfish', 'Glass Catfish',
     'Tank-bred. Completely see-through, bones and all. Shy -- keep six or more in gentle current.',
     12000, 'catfish-small', 'Kryptopterus vitreolus'),
    ('FSH-CAT-02', 'pictus-catfish', 'Pictus Catfish',
     'Tank-bred. Silver with black spots and very long whiskers. Fast, active -- and it eats neons at night.',
     25000, 'catfish-large', 'Pimelodus pictus'),
    ('FSH-CAT-03', 'upside-down-catfish', 'Upside-Down Catfish',
     'Tank-bred. Really does swim upside down. A small, peaceful synodontis.',
     20000, 'catfish-synodontis', 'Synodontis nigriventris'),
    ('FSH-CAT-04', 'striped-raphael-catfish', 'Striped Raphael Catfish',
     'Tank-bred. Black-and-white striped, armoured, and it croaks when picked up.',
     25000, 'catfish-large', 'Platydoras armatulus'),
    ('FSH-PLC-01', 'gold-nugget-pleco', 'Gold Nugget Pleco (L081)',
     'Wild-type import. Black with bright gold spots and gold fin tips. A warm, clean, fast-flowing tank.',
     180000, 'catfish-pleco-large', 'Baryancistrus xanthellus'),
    ('FSH-PLC-02', 'royal-pleco', 'Royal Pleco (L191)',
     'Wild-type import. Eats wood -- driftwood is part of its diet, not decoration. Grows past 40 cm.',
     250000, 'catfish-pleco-large', 'Panaque nigrolineatus'),
    ('FSH-PLC-03', 'snowball-pleco', 'Snowball Pleco (L201)',
     'Wild-type import. Black with white polka dots. A mid-sized pleco that stays under 16 cm.',
     120000, 'catfish-pleco-large', 'Hypancistrus inspector'),
    ('FSH-LCH-02', 'clown-loach', 'Clown Loach',
     'Sold at 5 cm. Grows slowly to 25-30 cm. A social snail-eater that needs a group and a big tank in the long run.',
     15000, 'loaches', 'Chromobotia macracanthus'),
    ('FSH-LCH-03', 'yoyo-loach', 'Yoyo Loach (Lohachata)',
     'Tank-bred. An Indian native from the Ganga basin. The markings spell "yoyo" on young fish.',
     12000, 'loaches', 'Botia almorhae'),
    ('FSH-LCH-04', 'zebra-loach', 'Zebra Loach',
     'Captive-bred. A Western Ghats endemic with fine zebra stripes. Peaceful and small for a botia.',
     15000, 'loaches', 'Botia striata'),
    ('FSH-LCH-05', 'dwarf-chain-loach', 'Dwarf Chain Loach',
     'Tank-bred. The smallest botia -- 6 cm, social and swims mid-water in a group.',
     20000, 'loaches', 'Ambastaia sidthimunki'),
    ('FSH-LCH-06', 'hillstream-loach', 'Reticulated Hillstream Loach',
     'Tank-bred. A flat, sucker-shaped loach that grazes smooth rocks. Needs cool, fast, oxygen-rich water.',
     30000, 'loaches', 'Sewellia lineolata'),
    ('FSH-SHK-01', 'rainbow-shark', 'Rainbow Shark',
     'Tank-bred. Dark body, red fins. Albino form available. One per tank.',
     8000, 'sharks-algae-eaters', 'Epalzeorhynchos frenatum'),
    ('FSH-SHK-02', 'red-tail-shark', 'Red Tail Shark',
     'Tank-bred. Velvet black with a fire-red tail. Striking, but it defends its patch hard.',
     12000, 'sharks-algae-eaters', 'Epalzeorhynchos bicolor'),
    ('FSH-SHK-03', 'bala-shark', 'Bala Shark',
     'Sold at 5 cm. Grows to 35 cm and needs a group. A fish for a very large tank.',
     10000, 'sharks-algae-eaters', 'Balantiocheilos melanopterus'),
    ('FSH-SHK-04', 'siamese-algae-eater', 'Siamese Algae Eater',
     'Tank-bred. One of the few fish that eats black beard algae. Often confused with the Chinese algae eater.',
     10000, 'sharks-algae-eaters', 'Crossocheilus oblongus'),
    ('FSH-SHK-05', 'chinese-algae-eater', 'Chinese Algae Eater',
     'Tank-bred. Gold form available. Useful when young; large adults can latch on to other fish.',
     5000, 'sharks-algae-eaters', 'Gyrinocheilus aymonieri'),
    ('FSH-GLD-01', 'oranda-goldfish', 'Oranda Goldfish',
     'Tank-bred. The fancy goldfish with a raised "hood" on the head. Red-cap, red, black, calico and blue colours.',
     35000, 'goldfish', 'Carassius auratus'),
    ('FSH-GLD-02', 'ryukin-goldfish', 'Ryukin Goldfish',
     'Tank-bred. A deep-bodied fancy goldfish with a high back and a long, split tail. Red-white and calico.',
     30000, 'goldfish', 'Carassius auratus'),
    ('FSH-GLD-03', 'black-moor-goldfish', 'Black Moor Goldfish',
     'Tank-bred. Velvet black with telescope eyes. The eyes are fragile -- no sharp décor.',
     20000, 'goldfish', 'Carassius auratus'),
    ('FSH-GLD-04', 'ranchu-goldfish', 'Ranchu Goldfish',
     'Tank-bred. The "king of goldfish" -- round, no dorsal fin, and a growing head. Keep with slow goldfish only.',
     80000, 'goldfish', 'Carassius auratus'),
    ('FSH-GLD-05', 'pearlscale-goldfish', 'Pearlscale Goldfish',
     'Tank-bred. Golf-ball body with raised, pearl-like scales. A slow swimmer.',
     40000, 'goldfish', 'Carassius auratus'),
    ('FSH-GLD-06', 'comet-goldfish', 'Comet Goldfish',
     'Tank-bred. A long-bodied, single-tail goldfish. Grows to 30 cm -- a pond fish, not a bowl fish.',
     6000, 'goldfish', 'Carassius auratus'),
    ('FSH-RBW-01', 'boesemani-rainbow', 'Boesemani Rainbowfish',
     'Tank-bred. Blue at the front, orange at the back. Colours deepen with age -- a fish that rewards patience.',
     25000, 'rainbowfish', 'Melanotaenia boesemani'),
    ('FSH-RBW-02', 'red-irian-rainbow', 'Red Irian Rainbowfish',
     'Tank-bred. Adult males turn deep red with a high back. Needs a long tank.',
     30000, 'rainbowfish', 'Glossolepis incisus'),
    ('FSH-RBW-03', 'threadfin-rainbow', 'Threadfin Rainbowfish',
     'Tank-bred. Tiny, with long threads flowing from its fins. Keep with other small, calm fish only.',
     20000, 'rainbowfish', 'Iriatherina werneri'),
    ('FSH-RBW-04', 'praecox-rainbow', 'Dwarf Neon Rainbowfish (Praecox)',
     'Tank-bred. Metallic blue body and red fins. A small, easy rainbowfish.',
     18000, 'rainbowfish', 'Melanotaenia praecox'),
    ('FSH-ODD-01', 'pea-puffer', 'Pea Puffer (Dwarf Puffer)',
     'An Indian native from Kerala and Karnataka. The smallest puffer in the world -- and it will not eat flake.',
     15000, 'oddballs', 'Carinotetraodon travancoricus'),
    ('FSH-ODD-02', 'black-ghost-knifefish', 'Black Ghost Knifefish',
     'Wild-type import. Senses its world with a weak electric field. Grows to 50 cm; nocturnal and shy.',
     60000, 'oddballs', 'Apteronotus albifrons'),
    ('FSH-ODD-03', 'fire-eel', 'Fire Eel',
     'Wild-type import. Red-striped spiny eel that grows up to a metre. Buries in sand; escapes through any gap.',
     90000, 'oddballs', 'Mastacembelus erythrotaenia'),
    ('FSH-ODD-04', 'tire-track-eel', 'Tire Track Eel (Baam)',
     'An Indian native spiny eel -- the baam of Bengal and Assam markets. Grows large; needs soft sand.',
     40000, 'oddballs', 'Mastacembelus armatus'),
    ('FSH-ODD-05', 'ornate-bichir', 'Ornate Bichir',
     'Tank-bred. A "living fossil" with lungs and a dragon-like pattern. Grows to 60 cm.',
     120000, 'oddballs', 'Polypterus ornatipinnis'),
    ('FSH-ODD-06', 'african-butterflyfish', 'African Butterflyfish',
     'Wild-type import. Lives right at the surface with wing-like fins. Eats insects -- and small surface fish.',
     30000, 'oddballs', 'Pantodon buchholzi')
  ) AS v(sku, slug, name, summary, price_minor, category, scientific_name);

